// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/:locale?/collections/:handle": {
    params: {
      "locale"?: string;
      "handle": string;
    };
  };
  "/:locale?/collections": {
    params: {
      "locale"?: string;
    };
  };
  "/:locale?/debug-availability": {
    params: {
      "locale"?: string;
    };
  };
  "/:locale?/checkout/success": {
    params: {
      "locale"?: string;
    };
  };
  "/:locale?/integration-test": {
    params: {
      "locale"?: string;
    };
  };
  "/:locale?/policies/:handle": {
    params: {
      "locale"?: string;
      "handle": string;
    };
  };
  "/:locale?/products/:handle": {
    params: {
      "locale"?: string;
      "handle": string;
    };
  };
  "/:locale?/policies": {
    params: {
      "locale"?: string;
    };
  };
  "/sitemap/:type/:page.xml": {
    params: {
      "type": string;
      "page": string;
    };
  };
  "/:locale?/pages/:handle": {
    params: {
      "locale"?: string;
      "handle": string;
    };
  };
  "/:locale?/checkout": {
    params: {
      "locale"?: string;
    };
  };
  "/:locale?/checkout/payment": {
    params: {
      "locale"?: string;
    };
  };
  "/:locale?/checkout/cancel": {
    params: {
      "locale"?: string;
    };
  };
  "/account/authorize": {
    params: {};
  };
  "/:locale?/contact": {
    params: {
      "locale"?: string;
    };
  };
  "/media/suppliers/*": {
    params: {
      "*": string;
    };
  };
  "/:locale?": {
    params: {
      "locale"?: string;
    };
  };
  "/:locale?/search": {
    params: {
      "locale"?: string;
    };
  };
  "/:locale?/cart": {
    params: {
      "locale"?: string;
    };
  };
  "/account/login": {
    params: {};
  };
  "/sitemap.xml": {
    params: {};
  };
  "/robots.txt": {
    params: {};
  };
  "/account": {
    params: {};
  };
  "/account/management": {
    params: {};
  };
  "/account/addresses": {
    params: {};
  };
  "/account/wishlist": {
    params: {};
  };
  "/account/profile": {
    params: {};
  };
  "/account/orders": {
    params: {};
  };
  "/account/orders/:id": {
    params: {
      "id": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/:locale?/collections/:handle" | "/:locale?/collections" | "/:locale?/debug-availability" | "/:locale?/checkout/success" | "/:locale?/integration-test" | "/:locale?/policies/:handle" | "/:locale?/products/:handle" | "/:locale?/policies" | "/sitemap/:type/:page.xml" | "/:locale?/pages/:handle" | "/:locale?/checkout" | "/:locale?/checkout/payment" | "/:locale?/checkout/cancel" | "/account/authorize" | "/:locale?/contact" | "/media/suppliers/*" | "/:locale?" | "/:locale?/search" | "/:locale?/cart" | "/account/login" | "/sitemap.xml" | "/robots.txt" | "/account" | "/account/management" | "/account/addresses" | "/account/wishlist" | "/account/profile" | "/account/orders" | "/account/orders/:id";
  };
  "routes/($locale).collections.$handle.tsx": {
    id: "routes/($locale).collections.$handle";
    page: "/:locale?/collections/:handle";
  };
  "routes/($locale).collections._index.tsx": {
    id: "routes/($locale).collections._index";
    page: "/:locale?/collections";
  };
  "routes/($locale).debug-availability.tsx": {
    id: "routes/($locale).debug-availability";
    page: "/:locale?/debug-availability";
  };
  "routes/($locale).checkout_.success.tsx": {
    id: "routes/($locale).checkout_.success";
    page: "/:locale?/checkout/success";
  };
  "routes/($locale).integration-test.tsx": {
    id: "routes/($locale).integration-test";
    page: "/:locale?/integration-test";
  };
  "routes/($locale).policies.$handle.tsx": {
    id: "routes/($locale).policies.$handle";
    page: "/:locale?/policies/:handle";
  };
  "routes/($locale).products.$handle.tsx": {
    id: "routes/($locale).products.$handle";
    page: "/:locale?/products/:handle";
  };
  "routes/($locale).policies._index.tsx": {
    id: "routes/($locale).policies._index";
    page: "/:locale?/policies";
  };
  "routes/sitemap.$type.$page[.xml].tsx": {
    id: "routes/sitemap.$type.$page[.xml]";
    page: "/sitemap/:type/:page.xml";
  };
  "routes/($locale).pages.$handle.tsx": {
    id: "routes/($locale).pages.$handle";
    page: "/:locale?/pages/:handle";
  };
  "routes/($locale).checkout.tsx": {
    id: "routes/($locale).checkout";
    page: "/:locale?/checkout" | "/:locale?/checkout/payment" | "/:locale?/checkout/cancel";
  };
  "routes/($locale).checkout.payment.tsx": {
    id: "routes/($locale).checkout.payment";
    page: "/:locale?/checkout/payment";
  };
  "routes/($locale).checkout.cancel.tsx": {
    id: "routes/($locale).checkout.cancel";
    page: "/:locale?/checkout/cancel";
  };
  "routes/account_.authorize.tsx": {
    id: "routes/account_.authorize";
    page: "/account/authorize";
  };
  "routes/($locale).contact.tsx": {
    id: "routes/($locale).contact";
    page: "/:locale?/contact";
  };
  "routes/media.suppliers.$.tsx": {
    id: "routes/media.suppliers.$";
    page: "/media/suppliers/*";
  };
  "routes/($locale)._index.tsx": {
    id: "routes/($locale)._index";
    page: "/:locale?";
  };
  "routes/($locale).search.tsx": {
    id: "routes/($locale).search";
    page: "/:locale?/search";
  };
  "routes/($locale).cart.tsx": {
    id: "routes/($locale).cart";
    page: "/:locale?/cart";
  };
  "routes/account_.login.tsx": {
    id: "routes/account_.login";
    page: "/account/login";
  };
  "routes/[sitemap.xml].tsx": {
    id: "routes/[sitemap.xml]";
    page: "/sitemap.xml";
  };
  "routes/[robots.txt].tsx": {
    id: "routes/[robots.txt]";
    page: "/robots.txt";
  };
  "routes/account.tsx": {
    id: "routes/account";
    page: "/account" | "/account/management" | "/account/addresses" | "/account/wishlist" | "/account/profile" | "/account/orders" | "/account/orders/:id";
  };
  "routes/account.management.tsx": {
    id: "routes/account.management";
    page: "/account/management";
  };
  "routes/account.addresses.tsx": {
    id: "routes/account.addresses";
    page: "/account/addresses";
  };
  "routes/account.wishlist.tsx": {
    id: "routes/account.wishlist";
    page: "/account/wishlist";
  };
  "routes/account.profile.tsx": {
    id: "routes/account.profile";
    page: "/account/profile";
  };
  "routes/account._index.tsx": {
    id: "routes/account._index";
    page: "/account";
  };
  "routes/account.orders.tsx": {
    id: "routes/account.orders";
    page: "/account/orders" | "/account/orders/:id";
  };
  "routes/account.orders._index.tsx": {
    id: "routes/account.orders._index";
    page: "/account/orders";
  };
  "routes/account.orders.$id.tsx": {
    id: "routes/account.orders.$id";
    page: "/account/orders/:id";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/($locale).collections.$handle": typeof import("./app/routes/($locale).collections.$handle.tsx");
  "routes/($locale).collections._index": typeof import("./app/routes/($locale).collections._index.tsx");
  "routes/($locale).debug-availability": typeof import("./app/routes/($locale).debug-availability.tsx");
  "routes/($locale).checkout_.success": typeof import("./app/routes/($locale).checkout_.success.tsx");
  "routes/($locale).integration-test": typeof import("./app/routes/($locale).integration-test.tsx");
  "routes/($locale).policies.$handle": typeof import("./app/routes/($locale).policies.$handle.tsx");
  "routes/($locale).products.$handle": typeof import("./app/routes/($locale).products.$handle.tsx");
  "routes/($locale).policies._index": typeof import("./app/routes/($locale).policies._index.tsx");
  "routes/sitemap.$type.$page[.xml]": typeof import("./app/routes/sitemap.$type.$page[.xml].tsx");
  "routes/($locale).pages.$handle": typeof import("./app/routes/($locale).pages.$handle.tsx");
  "routes/($locale).checkout": typeof import("./app/routes/($locale).checkout.tsx");
  "routes/($locale).checkout.payment": typeof import("./app/routes/($locale).checkout.payment.tsx");
  "routes/($locale).checkout.cancel": typeof import("./app/routes/($locale).checkout.cancel.tsx");
  "routes/account_.authorize": typeof import("./app/routes/account_.authorize.tsx");
  "routes/($locale).contact": typeof import("./app/routes/($locale).contact.tsx");
  "routes/media.suppliers.$": typeof import("./app/routes/media.suppliers.$.tsx");
  "routes/($locale)._index": typeof import("./app/routes/($locale)._index.tsx");
  "routes/($locale).search": typeof import("./app/routes/($locale).search.tsx");
  "routes/($locale).cart": typeof import("./app/routes/($locale).cart.tsx");
  "routes/account_.login": typeof import("./app/routes/account_.login.tsx");
  "routes/[sitemap.xml]": typeof import("./app/routes/[sitemap.xml].tsx");
  "routes/[robots.txt]": typeof import("./app/routes/[robots.txt].tsx");
  "routes/account": typeof import("./app/routes/account.tsx");
  "routes/account.management": typeof import("./app/routes/account.management.tsx");
  "routes/account.addresses": typeof import("./app/routes/account.addresses.tsx");
  "routes/account.wishlist": typeof import("./app/routes/account.wishlist.tsx");
  "routes/account.profile": typeof import("./app/routes/account.profile.tsx");
  "routes/account._index": typeof import("./app/routes/account._index.tsx");
  "routes/account.orders": typeof import("./app/routes/account.orders.tsx");
  "routes/account.orders._index": typeof import("./app/routes/account.orders._index.tsx");
  "routes/account.orders.$id": typeof import("./app/routes/account.orders.$id.tsx");
};